# Generated by Django 4.2.7 on 2023-11-20 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_alter_formtwo_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formtwo",
            old_name="phone",
            new_name="email",
        ),
    ]
